---
- name: Download Vector distribution
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.34.1/vector-{{ vector_version }}.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}.rpm"
    state: present
- name: Deploy Vector configuration
  ansible.builtin.template:
    src: vector.j2
    dest: "/etc/vector/vector.toml"
    mode: '0644'
  notify: Reload vector service

