apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: busybox
        image: busybox
        volumeMounts:
        - name: shared-data
          mountPath: /data
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /data/date.txt; sleep 5; done"]
      - name: multitool
        image: praqma/network-multitool
        volumeMounts:
        - name: shared-data
          mountPath: /data

